"""One-command v0.1 orchestration.

The default mode evaluates an existing media set (the safe path used for the
curated example).  ``--generate`` first calls the local FastAPI generation
matrix for one supplied product image, then feeds the resulting keyframes and
videos into the same mask-aware evaluator.  Generation remains an explicit
flag because it is GPU-expensive and must never be triggered accidentally by a
reporting command.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CONFIG = PROJECT_ROOT / "configs/phase2-comparison.json"
DEFAULT_INPUT = PROJECT_ROOT / "samples/example/input.png"


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, value: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2), encoding="utf-8")


def build_single_sample_config(base_path: Path, input_path: Path, campaign_prompt: str,
                               output_path: Path) -> Path:
    config = read_json(base_path)
    base_prompt = campaign_prompt.strip() or "premium product advertising"
    config["description"] = "Single-product v0.1 end-to-end run generated by run-v01-pipeline.py."
    config["prompts"]["image"] = config["prompts"]["image"] + "\nCampaign requirement: " + base_prompt
    config["prompts"]["video"] = config["prompts"]["video"] + "\nCampaign requirement: " + base_prompt
    config["samples"] = [{
        "id": "pipeline_product",
        "label": "Pipeline product",
        "source": str(input_path.resolve()),
        "generate_prompt": None,
        "micro_action": "a restrained studio highlight moves across the product while its identity remains fixed",
        "ground_truth": {
            "category": "unknown",
            "form_factor": "single product",
            "colors": [],
            "material": "",
            "finish": "",
            "closure": "",
            "container_count": 1,
            "ocr_text": [],
        },
    }]
    write_json(output_path, config)
    return output_path


def run(command: list[str], *, env: dict[str, str] | None = None) -> None:
    print("+", " ".join(command))
    subprocess.run(command, cwd=PROJECT_ROOT, env=env, check=True)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--prompt", default="premium luxury product advertisement")
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--run-id", default="pipeline-v01")
    parser.add_argument("--run-root", type=Path, default=PROJECT_ROOT / "runs/pipeline-v01")
    parser.add_argument("--output-root", type=Path, default=PROJECT_ROOT / "public/uploads/pipeline-v01")
    parser.add_argument("--service-url", default="http://127.0.0.1:8100")
    parser.add_argument("--generate", action="store_true",
                        help="Generate one product's keyframes/videos before evaluating")
    parser.add_argument("--vlm-model", choices=("none", "qwen3_vl", "internvl3_5_8b"), default="none")
    parser.add_argument("--vlm-path", type=Path, default=None)
    parser.add_argument("--request-timeout", type=int, default=2400)
    args = parser.parse_args()

    input_path = args.input.resolve()
    if not input_path.is_file():
        raise FileNotFoundError(input_path)
    config_path = args.config.resolve()
    run_root = args.run_root.resolve()
    output_root = args.output_root.resolve()
    keyframe_root = None
    video_root = None
    record_root = None
    if args.generate:
        config_path = build_single_sample_config(config_path, input_path, args.prompt, run_root / "pipeline-config.json")
        run([
            sys.executable, str(PROJECT_ROOT / "scripts/run-phase2-comparison.py"),
            "--config", str(config_path), "--base-url", args.service_url,
            "--output-root", str(output_root), "--run-root", str(run_root / "generation"),
            "--skip-vlm", "--skip-input-generation", "--request-timeout", str(args.request_timeout),
        ])
        keyframe_root = output_root / "_shared/keyframes"
        video_root = output_root / "_shared/videos"
        record_root = run_root / "generation"
    else:
        keyframe_root = output_root / "_shared/keyframes" if (output_root / "_shared/keyframes").is_dir() else PROJECT_ROOT / "samples/example/keyframes"
        video_root = output_root / "_shared/videos" if (output_root / "_shared/videos").is_dir() else PROJECT_ROOT / "samples/example/videos"
        record_root = PROJECT_ROOT / "samples/example/records"

    eval_command = [
        sys.executable, str(PROJECT_ROOT / "scripts/run-v01-evaluation.py"),
        "--config", str(config_path), "--input", str(input_path),
        "--keyframe-root", str(keyframe_root), "--video-root", str(video_root),
        "--record-root", str(record_root), "--output-root", str(run_root / "evaluation"),
        "--run-id", args.run_id, "--user-prompt", args.prompt,
    ]
    if args.vlm_model != "none":
        if args.vlm_path is None:
            raise ValueError("--vlm-path is required when --vlm-model is selected")
        eval_command += ["--vlm-model", args.vlm_model, "--vlm-path", str(args.vlm_path.resolve())]
    run(eval_command, env=dict(os.environ))


if __name__ == "__main__":
    main()
